In [1]:
import pandas as pd

In [2]:
import numpy as num

In [5]:
df=pd.read_csv("air-traffic-landings-statistics.csv")

In [6]:
df

,Activity Period,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Landing Aircraft Type,Aircraft Body Type,Aircraft Manufacturer,Aircraft Model,Aircraft Version,Landing Count,Total Landed Weight
0,201809,SkyWest Airlines,OO,United Airlines,UA,International,Canada,Passenger,Regional Jet,Bombardier,CRJ2,-,30,1410000
1,201809,Air Canada,AC,Air Canada,AC,International,Canada,Passenger,Narrow Body,Airbus,A320,-,125,17787978
2,201809,Japan Airlines,JL,Japan Airlines,JL,International,Asia,Passenger,Wide Body,Boeing,B773,-,30,16620000
3,201809,"COPA Airlines, Inc.",CM,"COPA Airlines, Inc.",CM,International,Central America,Passenger,Narrow Body,Boeing,B739,-,3,491700
4,201809,Hong Kong Airlines Limited,HX,Hong Kong Airlines Limited,HX,International,Asia,Passenger,Wide Body,Airbus,A359,-,16,7301712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22042,200507,SkyWest Airlines,OO,Delta Air Lines,DL,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,500,155,7285000
22043,200507,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,600,268,17956000
22044,200507,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,International,Canada,Passenger,Regional Jet,Bombardier,CRJ,600,62,4154000
22045,200507,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,700,1360,63920000
22046,200507,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Turbo Prop,Embraer,ERJ,120,1655,42699000

In [9]:
df.dtypes

Activity Period                 int64
Operating Airline              object
Operating Airline IATA Code    object
Published Airline              object
Published Airline IATA Code    object
GEO Summary                    object
GEO Region                     object
Landing Aircraft Type          object
Aircraft Body Type             object
Aircraft Manufacturer          object
Aircraft Model                 object
Aircraft Version               object
Landing Count                   int64
Total Landed Weight             int64
dtype: object

In [17]:
df.columns

Index(['Name', 'Age', 'Location'], dtype='object')

In [11]:
>>> df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Aritra'],
               'Age': [25, 30, 35],
                  'Location': ['Seattle', 'New York', 'Kona']},
                  index=([10, 20, 30]))

In [14]:
df.

AttributeError: 'DataFrame' object has no attribute 'age'

In [16]:
df.columns

Index(['Name', 'Age', 'Location'], dtype='object')